### ISSUE TITLE
BUILD FAILED 

### ISSUE THREAD

**Issue by cheikhounagueye** [AbdullahChauhan/Coronavirus-COVID-19-Tracker#1]
flutter doctor 
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.12.13+hotfix.9, on Microsoft Windows [version 10.0.18362.720], locale fr-FR)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[√] Android Studio (version 3.6)
[√] VS Code (version 1.44.0)
[√] Connected device (1 available)

• No issues found!

------------------------------------------------------------------------------------------------------------

flutter run --debug
Launching lib\main.dart on Orange Rise 55 in debug mode...

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:compileDebugJavaWithJavac'.
> Could not resolve all task dependencies for configuration ':app:debugCompileClasspath'.
   > Could not resolve project :flutter_plugin_android_lifecycle.
     Required by:
         project :app
      > Unable to find a matching variant of project :flutter_plugin_android_lifecycle:
          - Variant 'debugApiElements' capability android:flutter_plugin_android_lifecycle:unspecified:
              - Incompatible attribute:
                  - Required com.android.build.gradle.internal.dependency.AndroidTypeAttr 'Aar' and found incompatible value 'Apk'.
              - Other attributes:
                  - Required com.android.build.api.attributes.BuildTypeAttr 'debug' and found compatible value 'debug'.
                  - Found com.android.build.api.attributes.VariantAttr 'debug' but wasn't required.
                  - Required org.gradle.usage 'java-api' and found compatible value 'java-api'.
                  - Required org.jetbrains.kotlin.platform.type 'androidJvm' but no value provided.
          - Variant 'debugBundleElements' capability android:flutter_plugin_android_lifecycle:unspecified:
              - Incompatible attribute:
                  - Required org.gradle.usage 'java-api' and found incompatible value 'android-bundle'.
              - Other attributes:
                  - Required com.android.build.api.attributes.BuildTypeAttr 'debug' but no value provided.
                  - Found com.android.build.api.attributes.VariantAttr 'debug' but wasn't required.
                  - Required com.android.build.gradle.internal.dependency.AndroidTypeAttr 'Aar' but no value provided.
                  - Required org.jetbrains.kotlin.platform.type 'androidJvm' but no value provided.
          - Variant 'debugMetadataElements' capability android:flutter_plugin_android_lifecycle:unspecified:
              - Incompatible attribute:
                  - Required com.android.build.gradle.internal.dependency.AndroidTypeAttr 'Aar' and found incompatible value 'Metadata'.
              - Other attributes:
                  - Required com.android.build.api.attributes.BuildTypeAttr 'debug' and found compatible value 'debug'.
                  - Found com.android.build.api.attributes.VariantAttr 'debug' but wasn't required.
                  - Required org.gradle.usage 'java-api' but no value provided.
                  - Required org.jetbrains.kotlin.platform.type 'androidJvm' but no value provided.
          - Variant 'debugRuntimeElements' capability android:flutter_plugin_android_lifecycle:unspecified:
              - Incompatible attribute:
                  - Required com.android.build.gradle.internal.dependency.AndroidTypeAttr 'Aar' and found incompatible value 'Apk'.
              - Other attributes:
                  - Required com.android.build.api.attributes.BuildTypeAttr 'debug' and found compatible value 'debug'.
                  - Found com.android.build.api.attributes.VariantAttr 'debug' but wasn't required.
                  - Required org.gradle.usage 'java-api' and found compatible value 'java-runtime'.
                  - Required org.jetbrains.kotlin.platform.type 'androidJvm' but no value provided.
          - Variant 'profileApiElements' capability android:flutter_plugin_android_lifecycle:unspecified:
              - Incompatible attributes:
                  - Required com.android.build.api.attributes.BuildTypeAttr 'debug' and found incompatible value 'profile'.
                  - Required com.android.build.gradle.internal.dependency.AndroidTypeAttr 'Aar' and found incompatible value 'Apk'.
              - Other attributes:
                  - Found com.android.build.api.attributes.VariantAttr 'profile' but wasn't required.
                  - Required org.gradle.usage 'java-api' and found compatible value 'java-api'.
                  - Required org.jetbrains.kotlin.platform.type 'androidJvm' but no value provided.
          - Variant 'profileBundleElements' capability android:flutter_plugin_android_lifecycle:unspecified:
              - Incompatible attribute:
                  - Required org.gradle.usage 'java-api' and found incompatible value 'android-bundle'.
              - Other attributes:
                  - Required com.android.build.api.attributes.BuildTypeAttr 'debug' but no value provided.
                  - Found com.android.build.api.attributes.VariantAttr 'profile' but wasn't required.
                  - Required com.android.build.gradle.internal.dependency.AndroidTypeAttr 'Aar' but no value provided.
                  - Required org.jetbrains.kotlin.platform.type 'androidJvm' but no value provided.
          - Variant 'profileMetadataElements' capability android:flutter_plugin_android_lifecycle:unspecified:
              - Incompatible attributes:
                  - Required com.android.build.api.attributes.BuildTypeAttr 'debug' and found incompatible value 'profile'.
                  - Required com.android.build.gradle.internal.dependency.AndroidTypeAttr 'Aar' and found incompatible value 'Metadata'.
              - Other attributes:
                  - Found com.android.build.api.attributes.VariantAttr 'profile' but wasn't required.
                  - Required org.gradle.usage 'java-api' but no value provided.
                  - Required org.jetbrains.kotlin.platform.type 'androidJvm' but no value provided.
          - Variant 'profileRuntimeElements' capability android:flutter_plugin_android_lifecycle:unspecified:
              - Incompatible attributes:
                  - Required com.android.build.api.attributes.BuildTypeAttr 'debug' and found incompatible value 'profile'.
                  - Required com.android.build.gradle.internal.dependency.AndroidTypeAttr 'Aar' and found incompatible value 'Apk'.
              - Other attributes:
                  - Found com.android.build.api.attributes.VariantAttr 'profile' but wasn't required.
                  - Required org.gradle.usage 'java-api' and found compatible value 'java-runtime'.
                  - Required org.jetbrains.kotlin.platform.type 'androidJvm' but no value provided.
          - Variant 'releaseApiElements' capability android:flutter_plugin_android_lifecycle:unspecified:
              - Incompatible attributes:
                  - Required com.android.build.api.attributes.BuildTypeAttr 'debug' and found incompatible value 'release'.
                  - Required com.android.build.gradle.internal.dependency.AndroidTypeAttr 'Aar' and found incompatible value 'Apk'.
              - Other attributes:
                  - Found com.android.build.api.attributes.VariantAttr 'release' but wasn't required.
                  - Required org.gradle.usage 'java-api' and found compatible value 'java-api'.
                  - Required org.jetbrains.kotlin.platform.type 'androidJvm' but no value provided.
          - Variant 'releaseBundleElements' capability android:flutter_plugin_android_lifecycle:unspecified:
              - Incompatible attribute:
                  - Required org.gradle.usage 'java-api' and found incompatible value 'android-bundle'.
              - Other attributes:
                  - Required com.android.build.api.attributes.BuildTypeAttr 'debug' but no value provided.
                  - Found com.android.build.api.attributes.VariantAttr 'release' but wasn't required.
                  - Required com.android.build.gradle.internal.dependency.AndroidTypeAttr 'Aar' but no value provided.
                  - Required org.jetbrains.kotlin.platform.type 'androidJvm' but no value provided.
          - Variant 'releaseMetadataElements' capability android:flutter_plugin_android_lifecycle:unspecified:
              - Incompatible attributes:
                  - Required com.android.build.api.attributes.BuildTypeAttr 'debug' and found incompatible value 'release'.
                  - Required com.android.build.gradle.internal.dependency.AndroidTypeAttr 'Aar' and found incompatible value 'Metadata'.
              - Other attributes:
                  - Found com.android.build.api.attributes.VariantAttr 'release' but wasn't required.
                  - Required org.gradle.usage 'java-api' but no value provided.
                  - Required org.jetbrains.kotlin.platform.type 'androidJvm' but no value provided.
          - Variant 'releaseRuntimeElements' capability android:flutter_plugin_android_lifecycle:unspecified:
              - Incompatible attributes:
                  - Required com.android.build.api.attributes.BuildTypeAttr 'debug' and found incompatible value 'release'.
                  - Required com.android.build.gradle.internal.dependency.AndroidTypeAttr 'Aar' and found incompatible value 'Apk'.
              - Other attributes:
                  - Found com.android.build.api.attributes.VariantAttr 'release' but wasn't required.
                  - Required org.gradle.usage 'java-api' and found compatible value 'java-runtime'.
                  - Required org.jetbrains.kotlin.platform.type 'androidJvm' but no value provided.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.       

* Get more help at https://help.gradle.org

BUILD FAILED in 2s
Running Gradle task 'assembleDebug'...
Running Gradle task 'assembleDebug'... Done                         3,4s
Gradle task assembleDebug failed with exit code 1

**Comment by AbdullahChauhan** [comment]
Hey @cheikhounagueye 
This seems to be the most common issue in Flutter when you run a new project or run an existing project. `May be update your gradle version to latest.` Or better to open the issue in the official Flutter Repo.
